---
default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 9.0.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.1
    hooks:
      - id: mypy
        files: src
        additional_dependencies:
          - numpy>=1.21
          - sqlalchemy[mypy]
          - alembic
          - types-cachetools
        args: [--install-types, --non-interactive]
        # Note that using the --install-types is problematic if running in
        # parallel as mutating the pre-commit env at runtime breaks cache.
