---
version: '3.7'
services:
    eval:
        build: .
        depends_on:
          - postgres
        tty: true
        environment:
          - POSTGRES_USER
          - POSTGRES_PASSWORD
          - POSTGRES_HOST
          - POSTGRES_PORT
    postgres:
        image: postgres:latest
        restart: always
        environment:
          - POSTGRES_USER
          - POSTGRES_PASSWORD
          - POSTGRES_HOST
          - POSTGRES_PORT
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - "5432:${POSTGRES_PORT}"
        volumes:
          - "./postgres-data:/var/lib/postgresql/data"
...
