"""add_metric_name_unique_constraint

Revision ID: 512d9168f6c2
Revises: eaf7bb3598af
Create Date: 2024-03-27 14:18:55.504729

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "512d9168f6c2"
down_revision = "eaf7bb3598af"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "metric", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "metric", type_="unique")
    # ### end Alembic commands ###
