"""version unique constraint

Revision ID: eaf7bb3598af
Revises: 495f69cbfe6d
Create Date: 2024-03-05 16:19:47.447327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf7bb3598af'
down_revision = '495f69cbfe6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'version', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'version', type_='unique')
    # ### end Alembic commands ###
