branch-defaults:
  web-ui:
    environment: synthesized-webui-dev
    group_suffix: null
  master:
    environment: synthesized-webui
    group_suffix: null
global:
  application_name: synthesized-webui
  branch: null
  default_ec2_keyname: synthesized
  default_platform: Docker 18.06.1-ce
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
