---
name: Build-Lint-Test

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        id: setup-py
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Cache .env
        uses: actions/cache@v2
        with:
          path: .env
          key: ${{ runner.os }}-env-{{ steps.setup-py.outputs.python-version }}-${{ hashFiles('**/setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-env-{{ steps.setup-py.outputs.python-version }}-

      - name: Install dependencies
        run: |
          python -m venv .env
          source .env/bin/activate
          pip install -U pip
          pip install flake8 mypy

      - name: Lint
        run: |
          source .env/bin/activate
          python -m flake8 src
          python -m mypy src

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=synthesized-io
            -Dsonar.projectKey=synthesized-io_synthesized-insight
            -Dsonar.projectName=synthesized-insight
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=src/synthesized_insight/
            -Dsonar.tests=tests/
            -Dsonar.pullrequest.provider=github
            -Dsonar.pullrequest.github.repository=synthesized-io/synthesized-insight
            -Dsonar.pullrequest.github.endpoint=https://api.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
