---
name: Build-Lint-Test

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        id: setup-py
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m venv .env
          source .env/bin/activate
          pip install -U pip
          pip install .[test,dev]

      - name: Lint
        run: |
          source .env/bin/activate
          python -m flake8 src
          python -m mypy src

      - name: Run unit tests
        run: |
          source .env/bin/activate
          pytest -v --junitxml=test-results/junit.xml  --cov=src/synthesized_insight --cov-report=xml:coverage/cobertura.xml --cov-branch tests
          sed -ie 's#/home/runner/work/insight/insight#/github/workspace#g' coverage/cobertura.xml


      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=synthesized-io
            -Dsonar.projectKey=synthesized-io_synthesized-insight
            -Dsonar.projectName=synthesized-insight
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=src/synthesized_insight/
            -Dsonar.tests=tests/
            -Dsonar.python.xunit.reportPath=test-results/*.xml
            -Dsonar.python.coverage.reportPaths=coverage/*.xml
            -Dsonar.pullrequest.provider=github
            -Dsonar.pullrequest.github.repository=synthesized-io/synthesized-insight
            -Dsonar.pullrequest.github.endpoint=https://api.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
...