---
name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install pypa/build
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install build --user

      - name: Build wheel
        run: |
          python -m build --wheel --outdir dist/ .
          echo "WHEEL_PATH=$(ls dist/*.whl)" >> $GITHUB_ENV

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://upload.pypi.org/legacy/

      - name: Add to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            LICENSE.md
            README.md
            ${{ env.WHEEL_PATH }}
          body_path: CHANGELOG.md
...
